### ISSUE TITLE
Decoded image is blank (white)

### ISSUE THREAD

**Issue by chocolatkey** [oov/psd#15]
When decoding either of these PSDs:
https://drive.google.com/file/d/1djLG1FfOGbwa0nA_K3KSt33pgmUlm9vK/view?usp=sharing
https://drive.google.com/file/d/15kzcfoIYNyBoSMpf_ZNiV-txqqhr4Cbm/view?usp=sharing
the resulting image in completely white, even though when opened in e.g. Photoshop, it is not blank. There are no errors during decoding.

**Comment by oov** [comment]
This is due to the fact that the software that exported the image is not outputting the correct composited image data.
This package is working correctly.

PSD files contain not only layered images, but also composited image data.
Most software that is not interested in layers will display this composited image.
Try opening the image with [IfranView](https://www.irfanview.com/) or something similar.

**Comment by gtf35** [comment]
But what is the right way to get layer's perview to file(like png)?

**Comment by oov** [comment]
Unless there is a specific reason, it is preferred to use pre-composited image data.
(Of course, you won't get the desired results the image in question.)

The reason for this is obvious:
PSD files have so many features, such as text layers, adjustment layers, etc.
It is very difficult to draw this complex data accurately, and creating this composited image requires a very large program, a lot of memory, and CPU resources.

The cause of the problem is that the software that created the image did not output the correct composited image.
The only way to solve this problem is to create the preview image yourself.
If you are prepared to implement the same functionality as an image editing software like Photoshop for previewing, you can do it that way.

**Comment by chocolatkey** [comment]
As @oov without the precomposite image, it's basically impossible, even software such as Affinity Photo, which has been studying PSD format for years, cannot make it look identical.
The reason I opened this issue in the first place is because the file was made with Photoshop, and you would assume a file made by Photoshop would not be broken, but unfortunately it seems that is the case.

**Comment by gtf35** [comment]
Thank you for your answers. 

I see, the prerequisite for the correct work of the code in readme is that the correct composited image is required.

Is there the correct manual create preview demo here ?  @oov
