### ISSUE TITLE
PSB not decodable

### ISSUE THREAD

**Issue by chocolatkey** [oov/psd#16]
When trying to open very large PSB files like this one: https://drive.google.com/file/d/1kiLgXZcKpND2EenDpOJj8xCiN9Zg1T1_/view?usp=sharing

I get the error `psd: layer info read size mismatched. expected <number X> actual <number X>` where X is the same number both times. The files open fine in external viewers (e.g. IfranView, Affinity Photo).

**Comment by oov** [comment]
Are you using the latest revision?
That file opened without any problems in my environment.
(GOVERSION=go1.17 GOOS=windows GOARCH=amd64)

**Comment by oov** [comment]
I haven't gotten a response from you yet, but just in case, I've eliminated the size check mechanism.
Now that error will no longer occur.

This was originally introduced to detect errors in the program.
However, this would make an error just by the presence of useless margins,
even if the image data reading itself was successful.

I observed an error caused by margins in another case, so eliminated it.
