### ISSUE TITLE
Does it currently support changing the content of text layers? 

### ISSUE THREAD

**Issue by zhenzi0322** [oov/psd#18]
Is there any way to update the contents of a TypeLayer layer?

**Comment by oov** [comment]
You can, but it's not easy.
Because this package does not focus on saving PSD files, so there is no convenient mechanism for updating them.
And it is not easy to write a drawing process that can be used universally, since color formats such as RGB and CMYK and bit depths must be handled appropriately.

[Layer.Channel](https://github.com/oov/psd/blob/5db5eafcecbb41ccc7448e9ac1f782b0a9ae0702/layer.go#L24) contains raw data for each component of color(such as R, G, B, C, M, Y, K, etc.), you can be changed directly.
However, this data is saved in various layouts based on color bit depth.
[Channel.Picker](https://github.com/oov/psd/blob/5db5eafcecbb41ccc7448e9ac1f782b0a9ae0702/layer.go#L101) can be used to read pixel data.
This Picker is generated by [findGrayPicker](https://github.com/oov/psd/blob/master/picker.go#L27), so the code around it will give you an idea of how to access each piece of data.
